### PR TITLE
CUP 2

### PR DESCRIPTION
**Pull request by inebritov**
Resent instead of #165 PR. @kyakovenko, @evgsid please check it again.

### CODE REVIEW

**Comment by evgsid** [comment]
I have small remark, in regard values starts from `_`:
Software supported by omaha updater can provide different software-specific values starts from `_` symbol. Omaha client scans registry values and searches for all values starts from this sign and push it to server. In the previos pr was added two values `_numaccounts` and one else, which are exectly software-specific values.
It is possbile to add wildcard to request.xsd for all values `_*` ?

Here is code which adds application defined attributes:
https://github.com/google/omaha/blob/master/omaha/common/xml_parser.cc#L1360
In the `omaha/goopdate/app_manager.cc` omaha updater reads all registry values starts from `_` symbol.

**Comment by inebritov** [comment]
Technically seems that it's [possible](https://www.w3.org/TR/xmlschema-1/#Wildcards) but I have no time and full environment to test it with Omaha client, so it can take some time.

**Comment by evgsid** [comment]
Yes, exactly, I found this docs and it needs time to understand :)
I have no more remarks.

**Comment by mherrmann** [comment]
This PR works perfectly for me for 1.3.99. Thanks @inebritov!

**Pull request merged**
